# Generated by Django 4.0 on 2022-01-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(help_text='Enter Your Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Enter Your Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Enter Name', max_length=40, null=True),
        ),
    ]
